# Generated by Django 4.2.3 on 2023-07-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testimonials", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="testimonials",
            old_name="text",
            new_name="testimonial",
        ),
        migrations.AlterField(
            model_name="testimonials",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="testimonials",
            name="photo",
            field=models.ImageField(upload_to="photos/"),
        ),
    ]
